//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DkEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public int idEstado { get; set; }
        public string activo { get; set; }
        public string cancelado { get; set; }
        public int idEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
