//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DkEventos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participante()
        {
            this.ParticipantesPrincipais = new HashSet<ParticipantesPrincipai>();
        }
    
        public int idParticipante { get; set; }
        public string nome { get; set; }
        public string apelido { get; set; }
        public string grau_academico { get; set; }
        public string empresa { get; set; }
        public string trabalho { get; set; }
        public string data_nascimento { get; set; }
        public string sexo { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantesPrincipai> ParticipantesPrincipais { get; set; }
    }
}
